server:
  port: 8838
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3306/oj_usercenter?useSSL=false&serverTimezone=GMT%2B8
    hikari:
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
ribbon:
  eager-load:
    enabled: true
    clients: content-center
content-center:
  ribbon:
    NFLoadBalancerRuleClassName: cn.edu.nciae.usercenter.configuration.NacosWeightedRule