version: '3'
services:
  registrycenter:
    image: registry-center:stable.1.0
    ports:
      - "8848:8848"
    container_name: Registry-Center
  rocketmqsrv:
    image: apacherocketmq/rocketmq:4.5.1-alpine
    container_name: rmqserver
    ports:
      - "9876:9876"
    command: sh mqnamesrv
#    volumes:
#      - "./Docker/rocketmq/namesrv/logs:/home/rocketmq/logs"
#    depends_on:
#      - registrycenter
  rocketmqbkr:
    image: apacherocketmq/rocketmq:4.5.1-alpine
    container_name: rmqbroker
    ports:
      - "10911:10911"
      - "10909:10909"
      - "10912:10912"
    links:
      - rocketmqsrv:namesrv
    volumes:
      - "./Docker/rocketmq/broker/conf/broker.conf:/home/rocketmq/rocketmq-4.5.1/conf/broker.conf"
#      - "./Docker/rocketmq/broker/logs:/home/rocketmq/logs"
#      - "./Docker/rocketmq/broker/store:/home/rocketmq/store"
    depends_on:
      - rocketmqsrv
    command: sh mqbroker -n namesrv:9876 -c ../conf/broker.conf
  judgecenter:
    image: judge-center:test.1.0
    ports:
      - "8818:8818"
    links:
      - registrycenter:registrysrv
      - rocketmqsrv:namesrv
    depends_on:
      - registrycenter
      - rocketmqsrv
      - rocketmqbkr
    container_name: Judge-Center
  rmqconsole:
    image: styletang/rocketmq-console-ng
    ports:
      - "24300:8080"
    links:
      - rocketmqsrv:namesrv
    environment:
      JAVA_OPTS: -Drocketmq.namesrv.addr=namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false
    depends_on:
      - rocketmqsrv
      - rocketmqbkr
    container_name: rmqconsole
networks:
  default:
    external:
      name: nciae-oj