server:
  port: 8826
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    stream:
      rocketmq:
        binder:
          name-server: localhost:9876
        bindings:
          JudgeSubmissionSource:
            output:
              producer:
                # use to define the distributed transaction
                transactional: true
                group: tx-judge-submission-group
          CheckpointSource:
            output:
              producer:
                transactional: true
                group: tx-add-checkpoint-group
      bindings:
        JUDGE_RESULT_INPUT:
          destination: JUDGE_RESULT_OUTPUT
          group: tx-judge-result-group
        JudgeSubmissionSource:
          # use to figure out the topic
          destination: Judge-Submission
        CheckpointSource:
          destination: Add-Checkpoint
  datasource:
    url: jdbc:mysql://localhost:3306/oj_contentcenter
    hikari:
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
ribbon:
  eager-load:
    enabled: true
    clients: user-center
user-center:
  ribbon:
    NFLoadBalancerRuleClassName: cn.edu.nciae.contentcenter.configuration.NacosWeightedRule
rocketmq:
  name-server: localhost:9876
  producer:
    group: ContentCenterProducerGroup
logging:
  level:
    com.alibaba.nacos: error