server:
  port: 8818
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
        bindings:
          JudgeResultSource:
            output:
              producer:
                # use to define the distributed transaction
                transactional: true
                group: tx-judge-result-group
      bindings:
        JUDGE_SUBMISSION_INPUT:
          destination: JUDGE_SUBMISSION_OUTPUT
          group: tx-judge-submission-group
        CHECKPOINT_INPUT:
          destination: CHECKPOINT_INPUT
          group: tx-add-checkpoint-group
        JudgeResultSource:
          destination: Judge-Result
  datasource:
    url: jdbc:mysql://localhost:3306/oj_judgecenter
    hikari:
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: JudgeCenterProducerGroup
logging:
  level:
    com.alibaba.nacos: error
judge:
  system:
    #  A user with lower permission for security
    username: judger
    password: judger
  center:
    #  the dir use to store the compile result and output
    #  workDir: /data/judgecenter/workDir
    workDir: /Users/rexmao/Documents/RexStudio/NCIAE-OJ-Data/workDir
    #  the dir use to store the checkpoints
    #  checkpointDir: /data/judgecenter/checkpointDir
    checkpointDir: /Users/rexmao/Documents/RexStudio/NCIAE-OJ-Data/checkpointDir
