server:
  port: 8818
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        JUDGE_SUBMISSION_INPUT:
          destination: JUDGE_SUBMISSION_OUTPUT
          group: tx_judge_submission_group
  datasource:
    url: jdbc:mysql://localhost:3306/oj_judgecenter
    hikari:
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.alibaba.nacos: error
judge:
  center:
    #  the dir use to store the compile result and output
    #  workDir: /data/judgecenter/workDir
    workDir: /Users/rexmao/Documents/RexStudio/NCIAE-OJ-Data/workDir
    #  the dir use to store the checkpoints
    #  checkpointDir: /data/judgecenter/checkpointDir
    checkpointDir: /Users/rexmao/Documents/RexStudio/NCIAE-OJ-Data/checkpointDir
