/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_edu_nciae_judgecenter_manager_Runner */

#ifndef _Included_cn_edu_nciae_judgecenter_manager_Runner
#define _Included_cn_edu_nciae_judgecenter_manager_Runner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_edu_nciae_judgecenter_manager_Runner
 * Method:    getRuntimeResult
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;II)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_cn_edu_nciae_judgecenter_manager_Runner_getRuntimeResult
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
